/** NexTrade — admin-only demo settlement operations console. */
const Adminreview=(()=>{
'use strict';
let container=null,reviews=[],filter='pending',refreshTimer=null;
function el(tag,className,text){const n=document.createElement(tag);if(className)n.className=className;if(text!==undefined)n.textContent=text;return n}
function profile(){return window.AppState?AppState.get('profile'):null}
function isAdmin(){const p=profile();return Boolean(p&&p.role==='admin')}
function money(v){return window.Format&&typeof Format.currency==='function'?Format.currency(Number(v||0)):'$'+Number(v||0).toFixed(2)}
function relative(value){const ts=new Date(value).getTime();if(!Number.isFinite(ts))return'Unknown time';const s=Math.max(0,Math.floor((Date.now()-ts)/1000));if(s<60)return'Just now';const m=Math.floor(s/60);if(m<60)return m+'m ago';const h=Math.floor(m/60);if(h<24)return h+'h ago';return Math.floor(h/24)+'d ago'}
async function token(){if(!window.supabaseClient)throw new Error('Secure session unavailable');const {data,error}=await supabaseClient.auth.getSession();if(error)throw error;if(!data||!data.session||!data.session.access_token)throw new Error('Session expired');return data.session.access_token}
async function api(path,options={}){const access=await token();const response=await fetch(path,{...options,headers:{...(options.headers||{}),'Authorization':'Bearer '+access}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Admin request failed');return payload}
function tone(status){return status==='approved'?'success':status==='rejected'?'danger':'warning'}function label(status){return status==='approved'?'Approved':status==='rejected'?'Declined':'Pending'}function rail(railId){return{ETH_ERC20:'ERC-20',USDT_TRC20:'TRC-20',BTC:'Bitcoin'}[railId]||railId||'Demo rail'}
function shell(){container.innerHTML='';const page=el('section','admin-review-page');const hero=el('section','admin-review-hero');hero.appendChild(el('div','admin-review-eyebrow','Restricted operations'));hero.appendChild(el('h1','admin-review-title','Settlement review queue'));hero.appendChild(el('p','admin-review-copy','Every decision is ledger-backed. Approval credits the demo Spot balance through the existing balance derivation trigger; decline leaves the balance unchanged.'));const toolbar=el('div','admin-review-toolbar');const refresh=el('button','btn btn-secondary btn-sm','Refresh');refresh.type='button';const ri=el('i');ri.className='fas fa-rotate';refresh.prepend(ri);refresh.addEventListener('click',()=>load(true));const alerts=el('button','btn btn-secondary btn-sm','Enable phone alerts');alerts.type='button';alerts.id='admin-alert-btn';const bell=el('i');bell.className='fas fa-bell';alerts.prepend(bell);alerts.addEventListener('click',enablePush);const state=el('span','admin-alert-state','Optional');state.id='admin-alert-state';toolbar.append(refresh,alerts,state);hero.appendChild(toolbar);const metrics=el('section','admin-review-metrics');metrics.id='admin-review-metrics';const filters=el('div','admin-review-filters ui-filter-row');[['pending','Pending'],['approved','Approved'],['rejected','Declined'],['all','All']].forEach(([id,text])=>{const b=el('button','ui-filter-chip',text);b.type='button';b.dataset.filter=id;b.setAttribute('aria-pressed',String(filter===id));b.addEventListener('click',()=>{filter=id;filters.querySelectorAll('.ui-filter-chip').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.filter===filter)));renderList()});filters.appendChild(b)});const list=el('section','admin-review-list');list.id='admin-review-list';page.append(hero,metrics,filters,list);container.appendChild(page)}
function metric(name,value){const c=el('div','admin-metric');c.appendChild(el('div','admin-metric__label',name));c.appendChild(el('div','admin-metric__value',String(value)));return c}
function renderMetrics(){const h=document.getElementById('admin-review-metrics');if(!h)return;h.innerHTML='';h.append(metric('Pending',reviews.filter(x=>x.status==='pending').length),metric('Approved',reviews.filter(x=>x.status==='approved').length),metric('Declined',reviews.filter(x=>x.status==='rejected').length))}
function visible(){return filter==='all'?reviews:reviews.filter(x=>x.status===filter)}
function declinePanel(review,card){const existing=card.querySelector('.admin-decline-panel');if(existing){existing.remove();return}const panel=el('div','admin-decline-panel');const ta=el('textarea');ta.maxLength=300;ta.placeholder='Reason (optional)';const actions=el('div','admin-decline-panel__actions');const cancel=el('button','btn btn-secondary btn-sm','Cancel');cancel.type='button';cancel.addEventListener('click',()=>panel.remove());const confirm=el('button','btn btn-danger btn-sm','Confirm decline');confirm.type='button';confirm.addEventListener('click',()=>decide(review,'decline',ta.value.trim(),confirm));actions.append(cancel,confirm);panel.append(ta,actions);card.appendChild(panel);requestAnimationFrame(()=>ta.focus())}
function card(review){const c=el('article','admin-review-card');c.dataset.status=review.status;const top=el('div','admin-review-card__top');const who=el('div');who.appendChild(el('div','admin-review-card__email',review.requester_email||'Authenticated tester'));who.appendChild(el('div','admin-review-card__time',relative(review.submitted_at)));const value=el('div');value.appendChild(el('div','admin-review-card__amount',money(review.amount)));value.appendChild(el('div','admin-review-card__rail',rail(review.rail)));top.append(who,value);c.appendChild(top);c.appendChild(el('div','admin-review-ref',review.deposit_reference));const status=el('div','admin-review-card__status');const badge=el('span','status-badge',label(review.status));badge.dataset.tone=tone(review.status);status.appendChild(badge);if(review.reviewed_at)status.appendChild(el('span','admin-review-card__time','Reviewed '+relative(review.reviewed_at)));c.appendChild(status);if(review.status==='pending'){const actions=el('div','admin-review-actions');const approve=el('button','btn btn-success btn-sm','Approve');approve.type='button';approve.addEventListener('click',async()=>{const ok=window.Modal?await Modal.confirm({title:'Approve demo deposit?',message:money(review.amount)+' will be credited to this tester’s demo Spot balance.',confirmText:'Approve',cancelText:'Cancel',icon:'fa-circle-check'}):false;if(ok)await decide(review,'approve','',approve)});const decline=el('button','btn btn-danger btn-sm','Decline');decline.type='button';decline.addEventListener('click',()=>declinePanel(review,c));actions.append(approve,decline);c.appendChild(actions)}return c}
function renderList(){const h=document.getElementById('admin-review-list');if(!h)return;h.innerHTML='';const items=visible();if(!items.length){const empty=el('div','admin-review-empty');const i=el('i');i.className='fas fa-inbox';empty.append(i,document.createTextNode(filter==='pending'?'No pending settlement reviews.':'No reviews in this view.'));h.appendChild(empty);return}items.forEach(r=>h.appendChild(card(r)))}
async function load(announce=false){const h=document.getElementById('admin-review-list');if(h&&!reviews.length)h.innerHTML='<div class="admin-review-loading"><div class="admin-review-loading__row"></div><div class="admin-review-loading__row"></div><div class="admin-review-loading__row"></div></div>';try{const payload=await api(window.APP_CONFIG&&APP_CONFIG.apis&&APP_CONFIG.apis.adminDepositReviews||'/api/admin-deposit-reviews');reviews=Array.isArray(payload.reviews)?payload.reviews:[];renderMetrics();renderList();if(announce&&window.App)App.showSuccess('Review queue refreshed')}catch(error){if(window.App)App.showError(error.message||'Could not load review queue')}}
async function decide(review,decision,reason,button){if(!review||!review.id)return;button.disabled=true;try{const payload=await api(window.APP_CONFIG&&APP_CONFIG.apis&&APP_CONFIG.apis.adminDepositReviews||'/api/admin-deposit-reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reviewId:review.id,decision,reason:reason||null})});const updated=payload.review;reviews=reviews.map(x=>x.id===updated.id?updated:x);renderMetrics();renderList();if(window.App)App.showSuccess(decision==='approve'?'Demo deposit approved':'Demo deposit declined')}catch(error){button.disabled=false;if(window.App)App.showError(error.message||'Review decision failed')}}
function decodeKey(base64String){const padding='='.repeat((4-base64String.length%4)%4);const base64=(base64String+padding).replace(/-/g,'+').replace(/_/g,'/');const raw=window.atob(base64);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
async function enablePush(){const button=document.getElementById('admin-alert-btn');const state=document.getElementById('admin-alert-state');if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window)){if(window.App)App.showError('Push notifications are not supported on this browser.');return}button.disabled=true;try{const endpoint=window.APP_CONFIG&&APP_CONFIG.apis&&APP_CONFIG.apis.adminPush||'/api/admin-push';const config=await api(endpoint);if(!config.configured||!config.publicKey){state.textContent='Server keys not configured';state.dataset.enabled='false';if(window.App)App.showError('Phone alerts are built but VAPID server keys are not configured yet.');return}const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Notification permission was not granted');const registration=await navigator.serviceWorker.ready;let sub=await registration.pushManager.getSubscription();if(!sub)sub=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:decodeKey(config.publicKey)});await api(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subscription:sub.toJSON()})});button.textContent='Phone alerts enabled';state.textContent='Active on this device';state.dataset.enabled='true';if(window.App)App.showSuccess('Admin phone alerts enabled')}catch(error){if(window.App)App.showError(error.message||'Could not enable phone alerts')}finally{button.disabled=false}}
function render(target){container=target;if(!container)return;if(!isAdmin()){container.innerHTML='';const denied=el('div','admin-review-empty');const i=el('i');i.className='fas fa-lock';denied.append(i,document.createTextNode('Admin access required.'));container.appendChild(denied);return}shell();load(false);refreshTimer=setInterval(()=>load(false),30000)}
function cleanup(){if(refreshTimer){clearInterval(refreshTimer);refreshTimer=null}container=null}
return{render,cleanup,refresh:load};
})();
if(typeof window!=='undefined')window.Adminreview=Adminreview;
