#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(new URL('..',import.meta.url).pathname);const baselinePath=path.join(root,'SURFACE_DEBT_BASELINE.json');
const ignoredRoots=new Set(['.git','node_modules','vendor','api','server','scripts']);
function filesRecursive(dir=''){const abs=path.join(root,dir);return fs.readdirSync(abs,{withFileTypes:true}).flatMap(entry=>{const rel=path.join(dir,entry.name);if(entry.isDirectory()&&(ignoredRoots.has(entry.name)||rel.startsWith('vendor/')))return[];if(entry.isDirectory())return filesRecursive(rel);const n=rel.replaceAll('\\','/');return(n.endsWith('.js')||n.endsWith('.css'))?[n]:[];});}
const patterns={hardcodedWhiteText:/color\s*:\s*#(?:fff|ffffff)\b/gi,whiteAlphaText:/color\s*:\s*rgba\(\s*255\s*,\s*255\s*,\s*255\s*,/gi,whiteAlphaBackground:/background(?:-color)?\s*:\s*rgba\(\s*255\s*,\s*255\s*,\s*255\s*,/gi,semanticAlphaBackground:/background(?:-color)?\s*:\s*rgba\(\s*(?:59\s*,\s*130\s*,\s*246|16\s*,\s*185\s*,\s*129|245\s*,\s*158\s*,\s*11|139\s*,\s*92\s*,\s*246|239\s*,\s*68\s*,\s*68)\s*,/gi,transparentChartBackground:/background\s*:\s*\{\s*color\s*:\s*['"]transparent['"]\s*\}/gi};
function collect(){const counts=Object.fromEntries(Object.keys(patterns).map(k=>[k,0]));for(const file of filesRecursive()){const src=fs.readFileSync(path.join(root,file),'utf8');for(const[name,pattern]of Object.entries(patterns))counts[name]+=(src.match(pattern)||[]).length;}return{counts};}
const current=collect();
if(process.argv.includes('--write-baseline')){fs.writeFileSync(baselinePath,JSON.stringify({generatedAt:new Date().toISOString(),counts:current.counts},null,2)+'\n');console.log('Surface-debt baseline written.');console.log(JSON.stringify(current.counts,null,2));process.exit(0);}
if(!fs.existsSync(baselinePath)){console.error('Surface-debt baseline missing.');process.exit(1);}const baseline=JSON.parse(fs.readFileSync(baselinePath,'utf8'));const regressions=[];for(const[key,value]of Object.entries(current.counts)){const allowed=Number(baseline.counts?.[key]??0);if(value>allowed)regressions.push(`${key}: ${value} > baseline ${allowed}`);}if(current.counts.transparentChartBackground>0)regressions.push('market chart still uses a transparent theme-dependent background');console.log('Surface/transparency debt');console.log(JSON.stringify(current.counts,null,2));if(regressions.length){console.error(regressions.join('\n'));process.exit(1);}console.log('Surface debt ratchet did not increase.');
